//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 14.0.23107.0
// 
namespace TodoASMX.UWP.ASMXService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TodoItem", Namespace="http://www.xamarin.com/webservices/")]
    public partial class TodoItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string IDField;
        
        private string NameField;
        
        private string NotesField;
        
        private bool DoneField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Notes {
            get {
                return this.NotesField;
            }
            set {
                if ((object.ReferenceEquals(this.NotesField, value) != true)) {
                    this.NotesField = value;
                    this.RaisePropertyChanged("Notes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public bool Done {
            get {
                return this.DoneField;
            }
            set {
                if ((this.DoneField.Equals(value) != true)) {
                    this.DoneField = value;
                    this.RaisePropertyChanged("Done");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.xamarin.com/webservices/", ConfigurationName="ASMXService.TodoASMXServiceSoap")]
    public interface TodoASMXServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.xamarin.com/webservices/GetTodoItems", ReplyAction="*")]
        System.Threading.Tasks.Task<TodoASMX.UWP.ASMXService.GetTodoItemsResponse> GetTodoItemsAsync(TodoASMX.UWP.ASMXService.GetTodoItemsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.xamarin.com/webservices/CreateTodoItem", ReplyAction="*")]
        System.Threading.Tasks.Task<TodoASMX.UWP.ASMXService.CreateTodoItemResponse> CreateTodoItemAsync(TodoASMX.UWP.ASMXService.CreateTodoItemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.xamarin.com/webservices/EditTodoItem", ReplyAction="*")]
        System.Threading.Tasks.Task<TodoASMX.UWP.ASMXService.EditTodoItemResponse> EditTodoItemAsync(TodoASMX.UWP.ASMXService.EditTodoItemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.xamarin.com/webservices/DeleteTodoItem", ReplyAction="*")]
        System.Threading.Tasks.Task<TodoASMX.UWP.ASMXService.DeleteTodoItemResponse> DeleteTodoItemAsync(TodoASMX.UWP.ASMXService.DeleteTodoItemRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTodoItemsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTodoItems", Namespace="http://www.xamarin.com/webservices/", Order=0)]
        public TodoASMX.UWP.ASMXService.GetTodoItemsRequestBody Body;
        
        public GetTodoItemsRequest() {
        }
        
        public GetTodoItemsRequest(TodoASMX.UWP.ASMXService.GetTodoItemsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetTodoItemsRequestBody {
        
        public GetTodoItemsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTodoItemsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTodoItemsResponse", Namespace="http://www.xamarin.com/webservices/", Order=0)]
        public TodoASMX.UWP.ASMXService.GetTodoItemsResponseBody Body;
        
        public GetTodoItemsResponse() {
        }
        
        public GetTodoItemsResponse(TodoASMX.UWP.ASMXService.GetTodoItemsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.xamarin.com/webservices/")]
    public partial class GetTodoItemsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.ObjectModel.ObservableCollection<TodoASMX.UWP.ASMXService.TodoItem> GetTodoItemsResult;
        
        public GetTodoItemsResponseBody() {
        }
        
        public GetTodoItemsResponseBody(System.Collections.ObjectModel.ObservableCollection<TodoASMX.UWP.ASMXService.TodoItem> GetTodoItemsResult) {
            this.GetTodoItemsResult = GetTodoItemsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateTodoItemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateTodoItem", Namespace="http://www.xamarin.com/webservices/", Order=0)]
        public TodoASMX.UWP.ASMXService.CreateTodoItemRequestBody Body;
        
        public CreateTodoItemRequest() {
        }
        
        public CreateTodoItemRequest(TodoASMX.UWP.ASMXService.CreateTodoItemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.xamarin.com/webservices/")]
    public partial class CreateTodoItemRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TodoASMX.UWP.ASMXService.TodoItem item;
        
        public CreateTodoItemRequestBody() {
        }
        
        public CreateTodoItemRequestBody(TodoASMX.UWP.ASMXService.TodoItem item) {
            this.item = item;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateTodoItemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateTodoItemResponse", Namespace="http://www.xamarin.com/webservices/", Order=0)]
        public TodoASMX.UWP.ASMXService.CreateTodoItemResponseBody Body;
        
        public CreateTodoItemResponse() {
        }
        
        public CreateTodoItemResponse(TodoASMX.UWP.ASMXService.CreateTodoItemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CreateTodoItemResponseBody {
        
        public CreateTodoItemResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditTodoItemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditTodoItem", Namespace="http://www.xamarin.com/webservices/", Order=0)]
        public TodoASMX.UWP.ASMXService.EditTodoItemRequestBody Body;
        
        public EditTodoItemRequest() {
        }
        
        public EditTodoItemRequest(TodoASMX.UWP.ASMXService.EditTodoItemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.xamarin.com/webservices/")]
    public partial class EditTodoItemRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TodoASMX.UWP.ASMXService.TodoItem item;
        
        public EditTodoItemRequestBody() {
        }
        
        public EditTodoItemRequestBody(TodoASMX.UWP.ASMXService.TodoItem item) {
            this.item = item;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditTodoItemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditTodoItemResponse", Namespace="http://www.xamarin.com/webservices/", Order=0)]
        public TodoASMX.UWP.ASMXService.EditTodoItemResponseBody Body;
        
        public EditTodoItemResponse() {
        }
        
        public EditTodoItemResponse(TodoASMX.UWP.ASMXService.EditTodoItemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class EditTodoItemResponseBody {
        
        public EditTodoItemResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteTodoItemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteTodoItem", Namespace="http://www.xamarin.com/webservices/", Order=0)]
        public TodoASMX.UWP.ASMXService.DeleteTodoItemRequestBody Body;
        
        public DeleteTodoItemRequest() {
        }
        
        public DeleteTodoItemRequest(TodoASMX.UWP.ASMXService.DeleteTodoItemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.xamarin.com/webservices/")]
    public partial class DeleteTodoItemRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public DeleteTodoItemRequestBody() {
        }
        
        public DeleteTodoItemRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteTodoItemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteTodoItemResponse", Namespace="http://www.xamarin.com/webservices/", Order=0)]
        public TodoASMX.UWP.ASMXService.DeleteTodoItemResponseBody Body;
        
        public DeleteTodoItemResponse() {
        }
        
        public DeleteTodoItemResponse(TodoASMX.UWP.ASMXService.DeleteTodoItemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeleteTodoItemResponseBody {
        
        public DeleteTodoItemResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TodoASMXServiceSoapChannel : TodoASMX.UWP.ASMXService.TodoASMXServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TodoASMXServiceSoapClient : System.ServiceModel.ClientBase<TodoASMX.UWP.ASMXService.TodoASMXServiceSoap>, TodoASMX.UWP.ASMXService.TodoASMXServiceSoap {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TodoASMXServiceSoapClient() : 
                base(TodoASMXServiceSoapClient.GetDefaultBinding(), TodoASMXServiceSoapClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.TodoASMXServiceSoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TodoASMXServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(TodoASMXServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), TodoASMXServiceSoapClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TodoASMXServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TodoASMXServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TodoASMXServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TodoASMXServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TodoASMXServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TodoASMX.UWP.ASMXService.GetTodoItemsResponse> TodoASMX.UWP.ASMXService.TodoASMXServiceSoap.GetTodoItemsAsync(TodoASMX.UWP.ASMXService.GetTodoItemsRequest request) {
            return base.Channel.GetTodoItemsAsync(request);
        }
        
        public System.Threading.Tasks.Task<TodoASMX.UWP.ASMXService.GetTodoItemsResponse> GetTodoItemsAsync() {
            TodoASMX.UWP.ASMXService.GetTodoItemsRequest inValue = new TodoASMX.UWP.ASMXService.GetTodoItemsRequest();
            inValue.Body = new TodoASMX.UWP.ASMXService.GetTodoItemsRequestBody();
            return ((TodoASMX.UWP.ASMXService.TodoASMXServiceSoap)(this)).GetTodoItemsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TodoASMX.UWP.ASMXService.CreateTodoItemResponse> TodoASMX.UWP.ASMXService.TodoASMXServiceSoap.CreateTodoItemAsync(TodoASMX.UWP.ASMXService.CreateTodoItemRequest request) {
            return base.Channel.CreateTodoItemAsync(request);
        }
        
        public System.Threading.Tasks.Task<TodoASMX.UWP.ASMXService.CreateTodoItemResponse> CreateTodoItemAsync(TodoASMX.UWP.ASMXService.TodoItem item) {
            TodoASMX.UWP.ASMXService.CreateTodoItemRequest inValue = new TodoASMX.UWP.ASMXService.CreateTodoItemRequest();
            inValue.Body = new TodoASMX.UWP.ASMXService.CreateTodoItemRequestBody();
            inValue.Body.item = item;
            return ((TodoASMX.UWP.ASMXService.TodoASMXServiceSoap)(this)).CreateTodoItemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TodoASMX.UWP.ASMXService.EditTodoItemResponse> TodoASMX.UWP.ASMXService.TodoASMXServiceSoap.EditTodoItemAsync(TodoASMX.UWP.ASMXService.EditTodoItemRequest request) {
            return base.Channel.EditTodoItemAsync(request);
        }
        
        public System.Threading.Tasks.Task<TodoASMX.UWP.ASMXService.EditTodoItemResponse> EditTodoItemAsync(TodoASMX.UWP.ASMXService.TodoItem item) {
            TodoASMX.UWP.ASMXService.EditTodoItemRequest inValue = new TodoASMX.UWP.ASMXService.EditTodoItemRequest();
            inValue.Body = new TodoASMX.UWP.ASMXService.EditTodoItemRequestBody();
            inValue.Body.item = item;
            return ((TodoASMX.UWP.ASMXService.TodoASMXServiceSoap)(this)).EditTodoItemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TodoASMX.UWP.ASMXService.DeleteTodoItemResponse> TodoASMX.UWP.ASMXService.TodoASMXServiceSoap.DeleteTodoItemAsync(TodoASMX.UWP.ASMXService.DeleteTodoItemRequest request) {
            return base.Channel.DeleteTodoItemAsync(request);
        }
        
        public System.Threading.Tasks.Task<TodoASMX.UWP.ASMXService.DeleteTodoItemResponse> DeleteTodoItemAsync(string id) {
            TodoASMX.UWP.ASMXService.DeleteTodoItemRequest inValue = new TodoASMX.UWP.ASMXService.DeleteTodoItemRequest();
            inValue.Body = new TodoASMX.UWP.ASMXService.DeleteTodoItemRequestBody();
            inValue.Body.id = id;
            return ((TodoASMX.UWP.ASMXService.TodoASMXServiceSoap)(this)).DeleteTodoItemAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.TodoASMXServiceSoap)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.TodoASMXServiceSoap)) {
                return new System.ServiceModel.EndpointAddress("http://developer.xamarin.com:8081/TodoService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return TodoASMXServiceSoapClient.GetBindingForEndpoint(EndpointConfiguration.TodoASMXServiceSoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return TodoASMXServiceSoapClient.GetEndpointAddress(EndpointConfiguration.TodoASMXServiceSoap);
        }
        
        public enum EndpointConfiguration {
            
            TodoASMXServiceSoap,
        }
    }
}
