#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("WorkingWithListviewNative.Droid.Resource", IsApplication=true)]

namespace WorkingWithListviewNative.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.actionBarSize = global::WorkingWithListviewNative.Droid.Resource.Attribute.actionBarSize;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int cellback = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int cellback2 = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int CustomSelector = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int CustomSelector2 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int FlowerBuds = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int forms_forms = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int forms_native = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Fruits = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Legumes = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int native_native = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Vegetables = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050003
			public const int Image = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int Text = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int Text1 = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int Text2 = 2131034114;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int NativeAndroidCell = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int NativeAndroidListViewCell = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
	}
}
#pragma warning restore 1591
