#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.35317
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FormsGallery.Droid.Resource", IsApplication=true)]

namespace FormsGallery.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int abc_fade_in = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int abc_fade_out = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int abc_slide_in_bottom = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int abc_slide_in_top = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int abc_slide_out_bottom = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int abc_slide_out_top = 2130968581;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010014
			public const int actionBarDivider = 2130771988;
			
			// aapt resource value: 0x7f010015
			public const int actionBarItemBackground = 2130771989;
			
			// aapt resource value: 0x7f010013
			public const int actionBarSize = 2130771987;
			
			// aapt resource value: 0x7f010011
			public const int actionBarSplitStyle = 2130771985;
			
			// aapt resource value: 0x7f010010
			public const int actionBarStyle = 2130771984;
			
			// aapt resource value: 0x7f01000d
			public const int actionBarTabBarStyle = 2130771981;
			
			// aapt resource value: 0x7f01000c
			public const int actionBarTabStyle = 2130771980;
			
			// aapt resource value: 0x7f01000e
			public const int actionBarTabTextStyle = 2130771982;
			
			// aapt resource value: 0x7f010012
			public const int actionBarWidgetTheme = 2130771986;
			
			// aapt resource value: 0x7f01001b
			public const int actionButtonStyle = 2130771995;
			
			// aapt resource value: 0x7f01004c
			public const int actionDropDownStyle = 2130772044;
			
			// aapt resource value: 0x7f010053
			public const int actionLayout = 2130772051;
			
			// aapt resource value: 0x7f010016
			public const int actionMenuTextAppearance = 2130771990;
			
			// aapt resource value: 0x7f010017
			public const int actionMenuTextColor = 2130771991;
			
			// aapt resource value: 0x7f010041
			public const int actionModeBackground = 2130772033;
			
			// aapt resource value: 0x7f010040
			public const int actionModeCloseButtonStyle = 2130772032;
			
			// aapt resource value: 0x7f010043
			public const int actionModeCloseDrawable = 2130772035;
			
			// aapt resource value: 0x7f010045
			public const int actionModeCopyDrawable = 2130772037;
			
			// aapt resource value: 0x7f010044
			public const int actionModeCutDrawable = 2130772036;
			
			// aapt resource value: 0x7f010049
			public const int actionModeFindDrawable = 2130772041;
			
			// aapt resource value: 0x7f010046
			public const int actionModePasteDrawable = 2130772038;
			
			// aapt resource value: 0x7f01004b
			public const int actionModePopupWindowStyle = 2130772043;
			
			// aapt resource value: 0x7f010047
			public const int actionModeSelectAllDrawable = 2130772039;
			
			// aapt resource value: 0x7f010048
			public const int actionModeShareDrawable = 2130772040;
			
			// aapt resource value: 0x7f010042
			public const int actionModeSplitBackground = 2130772034;
			
			// aapt resource value: 0x7f01003f
			public const int actionModeStyle = 2130772031;
			
			// aapt resource value: 0x7f01004a
			public const int actionModeWebSearchDrawable = 2130772042;
			
			// aapt resource value: 0x7f01000f
			public const int actionOverflowButtonStyle = 2130771983;
			
			// aapt resource value: 0x7f010055
			public const int actionProviderClass = 2130772053;
			
			// aapt resource value: 0x7f010054
			public const int actionViewClass = 2130772052;
			
			// aapt resource value: 0x7f010071
			public const int activityChooserViewStyle = 2130772081;
			
			// aapt resource value: 0x7f010073
			public const int adSize = 2130772083;
			
			// aapt resource value: 0x7f010074
			public const int adSizes = 2130772084;
			
			// aapt resource value: 0x7f010075
			public const int adUnitId = 2130772085;
			
			// aapt resource value: 0x7f010034
			public const int background = 2130772020;
			
			// aapt resource value: 0x7f010036
			public const int backgroundSplit = 2130772022;
			
			// aapt resource value: 0x7f010035
			public const int backgroundStacked = 2130772021;
			
			// aapt resource value: 0x7f01001d
			public const int buttonBarButtonStyle = 2130771997;
			
			// aapt resource value: 0x7f01001c
			public const int buttonBarStyle = 2130771996;
			
			// aapt resource value: 0x7f010077
			public const int cameraBearing = 2130772087;
			
			// aapt resource value: 0x7f010078
			public const int cameraTargetLat = 2130772088;
			
			// aapt resource value: 0x7f010079
			public const int cameraTargetLng = 2130772089;
			
			// aapt resource value: 0x7f01007a
			public const int cameraTilt = 2130772090;
			
			// aapt resource value: 0x7f01007b
			public const int cameraZoom = 2130772091;
			
			// aapt resource value: 0x7f010037
			public const int customNavigationLayout = 2130772023;
			
			// aapt resource value: 0x7f010059
			public const int disableChildrenWhenDisabled = 2130772057;
			
			// aapt resource value: 0x7f01002d
			public const int displayOptions = 2130772013;
			
			// aapt resource value: 0x7f010033
			public const int divider = 2130772019;
			
			// aapt resource value: 0x7f010020
			public const int dividerHorizontal = 2130772000;
			
			// aapt resource value: 0x7f01005b
			public const int dividerPadding = 2130772059;
			
			// aapt resource value: 0x7f01001f
			public const int dividerVertical = 2130771999;
			
			// aapt resource value: 0x7f010026
			public const int dropDownListViewStyle = 2130772006;
			
			// aapt resource value: 0x7f01004d
			public const int dropdownListPreferredItemHeight = 2130772045;
			
			// aapt resource value: 0x7f010070
			public const int expandActivityOverflowButtonDrawable = 2130772080;
			
			// aapt resource value: 0x7f010000
			public const int externalRouteEnabledDrawable = 2130771968;
			
			// aapt resource value: 0x7f01002b
			public const int height = 2130772011;
			
			// aapt resource value: 0x7f010018
			public const int homeAsUpIndicator = 2130771992;
			
			// aapt resource value: 0x7f010038
			public const int homeLayout = 2130772024;
			
			// aapt resource value: 0x7f010031
			public const int icon = 2130772017;
			
			// aapt resource value: 0x7f01005f
			public const int iconifiedByDefault = 2130772063;
			
			// aapt resource value: 0x7f01003a
			public const int indeterminateProgressStyle = 2130772026;
			
			// aapt resource value: 0x7f01006f
			public const int initialActivityCount = 2130772079;
			
			// aapt resource value: 0x7f01005e
			public const int isLightTheme = 2130772062;
			
			// aapt resource value: 0x7f01003c
			public const int itemPadding = 2130772028;
			
			// aapt resource value: 0x7f010051
			public const int listChoiceBackgroundIndicator = 2130772049;
			
			// aapt resource value: 0x7f010027
			public const int listPopupWindowStyle = 2130772007;
			
			// aapt resource value: 0x7f010021
			public const int listPreferredItemHeight = 2130772001;
			
			// aapt resource value: 0x7f010023
			public const int listPreferredItemHeightLarge = 2130772003;
			
			// aapt resource value: 0x7f010022
			public const int listPreferredItemHeightSmall = 2130772002;
			
			// aapt resource value: 0x7f010024
			public const int listPreferredItemPaddingLeft = 2130772004;
			
			// aapt resource value: 0x7f010025
			public const int listPreferredItemPaddingRight = 2130772005;
			
			// aapt resource value: 0x7f010032
			public const int logo = 2130772018;
			
			// aapt resource value: 0x7f010076
			public const int mapType = 2130772086;
			
			// aapt resource value: 0x7f010001
			public const int mediaRouteButtonStyle = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int mediaRouteConnectingDrawable = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int mediaRouteOffDrawable = 2130771970;
			
			// aapt resource value: 0x7f010004
			public const int mediaRouteOnDrawable = 2130771972;
			
			// aapt resource value: 0x7f01002c
			public const int navigationMode = 2130772012;
			
			// aapt resource value: 0x7f01003e
			public const int paddingEnd = 2130772030;
			
			// aapt resource value: 0x7f01003d
			public const int paddingStart = 2130772029;
			
			// aapt resource value: 0x7f010050
			public const int panelMenuListTheme = 2130772048;
			
			// aapt resource value: 0x7f01004f
			public const int panelMenuListWidth = 2130772047;
			
			// aapt resource value: 0x7f01004e
			public const int popupMenuStyle = 2130772046;
			
			// aapt resource value: 0x7f010058
			public const int popupPromptView = 2130772056;
			
			// aapt resource value: 0x7f01003b
			public const int progressBarPadding = 2130772027;
			
			// aapt resource value: 0x7f010039
			public const int progressBarStyle = 2130772025;
			
			// aapt resource value: 0x7f010056
			public const int prompt = 2130772054;
			
			// aapt resource value: 0x7f010060
			public const int queryHint = 2130772064;
			
			// aapt resource value: 0x7f010061
			public const int searchDropdownBackground = 2130772065;
			
			// aapt resource value: 0x7f01006a
			public const int searchResultListItemHeight = 2130772074;
			
			// aapt resource value: 0x7f01006e
			public const int searchViewAutoCompleteTextView = 2130772078;
			
			// aapt resource value: 0x7f010062
			public const int searchViewCloseIcon = 2130772066;
			
			// aapt resource value: 0x7f010066
			public const int searchViewEditQuery = 2130772070;
			
			// aapt resource value: 0x7f010067
			public const int searchViewEditQueryBackground = 2130772071;
			
			// aapt resource value: 0x7f010063
			public const int searchViewGoIcon = 2130772067;
			
			// aapt resource value: 0x7f010064
			public const int searchViewSearchIcon = 2130772068;
			
			// aapt resource value: 0x7f010068
			public const int searchViewTextField = 2130772072;
			
			// aapt resource value: 0x7f010069
			public const int searchViewTextFieldRight = 2130772073;
			
			// aapt resource value: 0x7f010065
			public const int searchViewVoiceIcon = 2130772069;
			
			// aapt resource value: 0x7f01001e
			public const int selectableItemBackground = 2130771998;
			
			// aapt resource value: 0x7f010052
			public const int showAsAction = 2130772050;
			
			// aapt resource value: 0x7f01005a
			public const int showDividers = 2130772058;
			
			// aapt resource value: 0x7f01005d
			public const int spinnerDropDownItemStyle = 2130772061;
			
			// aapt resource value: 0x7f010057
			public const int spinnerMode = 2130772055;
			
			// aapt resource value: 0x7f01005c
			public const int spinnerStyle = 2130772060;
			
			// aapt resource value: 0x7f01002e
			public const int subtitle = 2130772014;
			
			// aapt resource value: 0x7f010030
			public const int subtitleTextStyle = 2130772016;
			
			// aapt resource value: 0x7f010072
			public const int textAllCaps = 2130772082;
			
			// aapt resource value: 0x7f010019
			public const int textAppearanceLargePopupMenu = 2130771993;
			
			// aapt resource value: 0x7f010028
			public const int textAppearanceListItem = 2130772008;
			
			// aapt resource value: 0x7f010029
			public const int textAppearanceListItemSmall = 2130772009;
			
			// aapt resource value: 0x7f01006c
			public const int textAppearanceSearchResultSubtitle = 2130772076;
			
			// aapt resource value: 0x7f01006b
			public const int textAppearanceSearchResultTitle = 2130772075;
			
			// aapt resource value: 0x7f01001a
			public const int textAppearanceSmallPopupMenu = 2130771994;
			
			// aapt resource value: 0x7f01006d
			public const int textColorSearchUrl = 2130772077;
			
			// aapt resource value: 0x7f01002a
			public const int title = 2130772010;
			
			// aapt resource value: 0x7f01002f
			public const int titleTextStyle = 2130772015;
			
			// aapt resource value: 0x7f01007c
			public const int uiCompass = 2130772092;
			
			// aapt resource value: 0x7f01007d
			public const int uiRotateGestures = 2130772093;
			
			// aapt resource value: 0x7f01007e
			public const int uiScrollGestures = 2130772094;
			
			// aapt resource value: 0x7f01007f
			public const int uiTiltGestures = 2130772095;
			
			// aapt resource value: 0x7f010080
			public const int uiZoomControls = 2130772096;
			
			// aapt resource value: 0x7f010081
			public const int uiZoomGestures = 2130772097;
			
			// aapt resource value: 0x7f010082
			public const int useViewLifecycle = 2130772098;
			
			// aapt resource value: 0x7f010005
			public const int windowActionBar = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int windowActionBarOverlay = 2130771974;
			
			// aapt resource value: 0x7f01000b
			public const int windowFixedHeightMajor = 2130771979;
			
			// aapt resource value: 0x7f010009
			public const int windowFixedHeightMinor = 2130771977;
			
			// aapt resource value: 0x7f010008
			public const int windowFixedWidthMajor = 2130771976;
			
			// aapt resource value: 0x7f01000a
			public const int windowFixedWidthMinor = 2130771978;
			
			// aapt resource value: 0x7f010007
			public const int windowSplitActionBar = 2130771975;
			
			// aapt resource value: 0x7f010083
			public const int zOrderOnTop = 2130772099;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f080000
			public const int abc_action_bar_embed_tabs_pre_jb = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int abc_action_bar_expanded_action_views_exclusive = 2131230721;
			
			// aapt resource value: 0x7f080005
			public const int abc_config_actionMenuItemAllCaps = 2131230725;
			
			// aapt resource value: 0x7f080004
			public const int abc_config_allowActionMenuItemTextWithIcon = 2131230724;
			
			// aapt resource value: 0x7f080003
			public const int abc_config_showMenuShortcutsWhenKeyboardPresent = 2131230723;
			
			// aapt resource value: 0x7f080002
			public const int abc_split_action_bar_is_narrow = 2131230722;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f09000d
			public const int abc_search_url_text_holo = 2131296269;
			
			// aapt resource value: 0x7f090000
			public const int abc_search_url_text_normal = 2131296256;
			
			// aapt resource value: 0x7f090002
			public const int abc_search_url_text_pressed = 2131296258;
			
			// aapt resource value: 0x7f090001
			public const int abc_search_url_text_selected = 2131296257;
			
			// aapt resource value: 0x7f09000c
			public const int common_action_bar_splitter = 2131296268;
			
			// aapt resource value: 0x7f090003
			public const int common_signin_btn_dark_text_default = 2131296259;
			
			// aapt resource value: 0x7f090005
			public const int common_signin_btn_dark_text_disabled = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int common_signin_btn_dark_text_focused = 2131296262;
			
			// aapt resource value: 0x7f090004
			public const int common_signin_btn_dark_text_pressed = 2131296260;
			
			// aapt resource value: 0x7f09000b
			public const int common_signin_btn_default_background = 2131296267;
			
			// aapt resource value: 0x7f090007
			public const int common_signin_btn_light_text_default = 2131296263;
			
			// aapt resource value: 0x7f090009
			public const int common_signin_btn_light_text_disabled = 2131296265;
			
			// aapt resource value: 0x7f09000a
			public const int common_signin_btn_light_text_focused = 2131296266;
			
			// aapt resource value: 0x7f090008
			public const int common_signin_btn_light_text_pressed = 2131296264;
			
			// aapt resource value: 0x7f09000e
			public const int common_signin_btn_text_dark = 2131296270;
			
			// aapt resource value: 0x7f09000f
			public const int common_signin_btn_text_light = 2131296271;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f0a0002
			public const int abc_action_bar_default_height = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int abc_action_bar_icon_vertical_padding = 2131361795;
			
			// aapt resource value: 0x7f0a000a
			public const int abc_action_bar_progress_bar_size = 2131361802;
			
			// aapt resource value: 0x7f0a0009
			public const int abc_action_bar_stacked_max_height = 2131361801;
			
			// aapt resource value: 0x7f0a0001
			public const int abc_action_bar_stacked_tab_max_width = 2131361793;
			
			// aapt resource value: 0x7f0a0007
			public const int abc_action_bar_subtitle_bottom_margin = 2131361799;
			
			// aapt resource value: 0x7f0a0005
			public const int abc_action_bar_subtitle_text_size = 2131361797;
			
			// aapt resource value: 0x7f0a0006
			public const int abc_action_bar_subtitle_top_margin = 2131361798;
			
			// aapt resource value: 0x7f0a0004
			public const int abc_action_bar_title_text_size = 2131361796;
			
			// aapt resource value: 0x7f0a0008
			public const int abc_action_button_min_width = 2131361800;
			
			// aapt resource value: 0x7f0a0000
			public const int abc_config_prefDialogWidth = 2131361792;
			
			// aapt resource value: 0x7f0a0010
			public const int abc_dropdownitem_icon_width = 2131361808;
			
			// aapt resource value: 0x7f0a000e
			public const int abc_dropdownitem_text_padding_left = 2131361806;
			
			// aapt resource value: 0x7f0a000f
			public const int abc_dropdownitem_text_padding_right = 2131361807;
			
			// aapt resource value: 0x7f0a000b
			public const int abc_panel_menu_list_width = 2131361803;
			
			// aapt resource value: 0x7f0a000d
			public const int abc_search_view_preferred_width = 2131361805;
			
			// aapt resource value: 0x7f0a000c
			public const int abc_search_view_text_min_width = 2131361804;
			
			// aapt resource value: 0x7f0a0013
			public const int dialog_fixed_height_major = 2131361811;
			
			// aapt resource value: 0x7f0a0014
			public const int dialog_fixed_height_minor = 2131361812;
			
			// aapt resource value: 0x7f0a0011
			public const int dialog_fixed_width_major = 2131361809;
			
			// aapt resource value: 0x7f0a0012
			public const int dialog_fixed_width_minor = 2131361810;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int abc_ab_bottom_solid_dark_holo = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int abc_ab_bottom_solid_light_holo = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int abc_ab_bottom_transparent_dark_holo = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int abc_ab_bottom_transparent_light_holo = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int abc_ab_share_pack_holo_dark = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int abc_ab_share_pack_holo_light = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int abc_ab_solid_dark_holo = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int abc_ab_solid_light_holo = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int abc_ab_stacked_solid_dark_holo = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int abc_ab_stacked_solid_light_holo = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int abc_ab_stacked_transparent_dark_holo = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int abc_ab_stacked_transparent_light_holo = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int abc_ab_transparent_dark_holo = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int abc_ab_transparent_light_holo = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int abc_cab_background_bottom_holo_dark = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int abc_cab_background_bottom_holo_light = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int abc_cab_background_top_holo_dark = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int abc_cab_background_top_holo_light = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int abc_ic_ab_back_holo_dark = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int abc_ic_ab_back_holo_light = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int abc_ic_cab_done_holo_dark = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int abc_ic_cab_done_holo_light = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int abc_ic_clear = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int abc_ic_clear_disabled = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int abc_ic_clear_holo_light = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int abc_ic_clear_normal = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int abc_ic_clear_search_api_disabled_holo_light = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int abc_ic_clear_search_api_holo_light = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int abc_ic_commit_search_api_holo_dark = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int abc_ic_commit_search_api_holo_light = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int abc_ic_go = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int abc_ic_go_search_api_holo_light = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int abc_ic_menu_moreoverflow_normal_holo_dark = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int abc_ic_menu_moreoverflow_normal_holo_light = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int abc_ic_menu_share_holo_dark = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int abc_ic_menu_share_holo_light = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int abc_ic_search = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int abc_ic_search_api_holo_light = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int abc_ic_voice_search = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int abc_ic_voice_search_api_holo_light = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int abc_item_background_holo_dark = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int abc_item_background_holo_light = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int abc_list_divider_holo_dark = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int abc_list_divider_holo_light = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int abc_list_focused_holo = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int abc_list_longpressed_holo = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int abc_list_pressed_holo_dark = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int abc_list_pressed_holo_light = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int abc_list_selector_background_transition_holo_dark = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int abc_list_selector_background_transition_holo_light = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int abc_list_selector_disabled_holo_dark = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int abc_list_selector_disabled_holo_light = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int abc_list_selector_holo_dark = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int abc_list_selector_holo_light = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int abc_menu_dropdown_panel_holo_dark = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int abc_menu_dropdown_panel_holo_light = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int abc_menu_hardkey_panel_holo_dark = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int abc_menu_hardkey_panel_holo_light = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int abc_search_dropdown_dark = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int abc_search_dropdown_light = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int abc_spinner_ab_default_holo_dark = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int abc_spinner_ab_default_holo_light = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int abc_spinner_ab_disabled_holo_dark = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int abc_spinner_ab_disabled_holo_light = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int abc_spinner_ab_focused_holo_dark = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int abc_spinner_ab_focused_holo_light = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int abc_spinner_ab_holo_dark = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int abc_spinner_ab_holo_light = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int abc_spinner_ab_pressed_holo_dark = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int abc_spinner_ab_pressed_holo_light = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int abc_tab_indicator_ab_holo = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int abc_tab_selected_focused_holo = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int abc_tab_selected_holo = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int abc_tab_selected_pressed_holo = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int abc_tab_unselected_pressed_holo = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int abc_textfield_search_default_holo_dark = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int abc_textfield_search_default_holo_light = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int abc_textfield_search_right_default_holo_dark = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int abc_textfield_search_right_default_holo_light = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int abc_textfield_search_right_selected_holo_dark = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int abc_textfield_search_right_selected_holo_light = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int abc_textfield_search_selected_holo_dark = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int abc_textfield_search_selected_holo_light = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int abc_textfield_searchview_holo_dark = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int abc_textfield_searchview_holo_light = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int abc_textfield_searchview_right_holo_dark = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int abc_textfield_searchview_right_holo_light = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int common_signin_btn_icon_dark = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int common_signin_btn_icon_disabled_dark = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int common_signin_btn_icon_disabled_focus_dark = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int common_signin_btn_icon_disabled_focus_light = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int common_signin_btn_icon_disabled_light = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int common_signin_btn_icon_focus_dark = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int common_signin_btn_icon_focus_light = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int common_signin_btn_icon_light = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int common_signin_btn_icon_normal_dark = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int common_signin_btn_icon_normal_light = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int common_signin_btn_icon_pressed_dark = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int common_signin_btn_icon_pressed_light = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int common_signin_btn_text_dark = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int common_signin_btn_text_disabled_dark = 2130837604;
			
			// aapt resource value: 0x7f020065
			public const int common_signin_btn_text_disabled_focus_dark = 2130837605;
			
			// aapt resource value: 0x7f020066
			public const int common_signin_btn_text_disabled_focus_light = 2130837606;
			
			// aapt resource value: 0x7f020067
			public const int common_signin_btn_text_disabled_light = 2130837607;
			
			// aapt resource value: 0x7f020068
			public const int common_signin_btn_text_focus_dark = 2130837608;
			
			// aapt resource value: 0x7f020069
			public const int common_signin_btn_text_focus_light = 2130837609;
			
			// aapt resource value: 0x7f02006a
			public const int common_signin_btn_text_light = 2130837610;
			
			// aapt resource value: 0x7f02006b
			public const int common_signin_btn_text_normal_dark = 2130837611;
			
			// aapt resource value: 0x7f02006c
			public const int common_signin_btn_text_normal_light = 2130837612;
			
			// aapt resource value: 0x7f02006d
			public const int common_signin_btn_text_pressed_dark = 2130837613;
			
			// aapt resource value: 0x7f02006e
			public const int common_signin_btn_text_pressed_light = 2130837614;
			
			// aapt resource value: 0x7f02006f
			public const int ic_plusone_medium_off_client = 2130837615;
			
			// aapt resource value: 0x7f020070
			public const int ic_plusone_small_off_client = 2130837616;
			
			// aapt resource value: 0x7f020071
			public const int ic_plusone_standard_off_client = 2130837617;
			
			// aapt resource value: 0x7f020072
			public const int ic_plusone_tall_off_client = 2130837618;
			
			// aapt resource value: 0x7f020073
			public const int Icon = 2130837619;
			
			// aapt resource value: 0x7f020074
			public const int ide_xamarin_studio = 2130837620;
			
			// aapt resource value: 0x7f020075
			public const int mr_ic_audio_vol = 2130837621;
			
			// aapt resource value: 0x7f020076
			public const int mr_ic_media_route_connecting_holo_dark = 2130837622;
			
			// aapt resource value: 0x7f020077
			public const int mr_ic_media_route_connecting_holo_light = 2130837623;
			
			// aapt resource value: 0x7f020078
			public const int mr_ic_media_route_disabled_holo_dark = 2130837624;
			
			// aapt resource value: 0x7f020079
			public const int mr_ic_media_route_disabled_holo_light = 2130837625;
			
			// aapt resource value: 0x7f02007a
			public const int mr_ic_media_route_holo_dark = 2130837626;
			
			// aapt resource value: 0x7f02007b
			public const int mr_ic_media_route_holo_light = 2130837627;
			
			// aapt resource value: 0x7f02007c
			public const int mr_ic_media_route_off_holo_dark = 2130837628;
			
			// aapt resource value: 0x7f02007d
			public const int mr_ic_media_route_off_holo_light = 2130837629;
			
			// aapt resource value: 0x7f02007e
			public const int mr_ic_media_route_on_0_holo_dark = 2130837630;
			
			// aapt resource value: 0x7f02007f
			public const int mr_ic_media_route_on_0_holo_light = 2130837631;
			
			// aapt resource value: 0x7f020080
			public const int mr_ic_media_route_on_1_holo_dark = 2130837632;
			
			// aapt resource value: 0x7f020081
			public const int mr_ic_media_route_on_1_holo_light = 2130837633;
			
			// aapt resource value: 0x7f020082
			public const int mr_ic_media_route_on_2_holo_dark = 2130837634;
			
			// aapt resource value: 0x7f020083
			public const int mr_ic_media_route_on_2_holo_light = 2130837635;
			
			// aapt resource value: 0x7f020084
			public const int mr_ic_media_route_on_holo_dark = 2130837636;
			
			// aapt resource value: 0x7f020085
			public const int mr_ic_media_route_on_holo_light = 2130837637;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07001f
			public const int action_bar = 2131165215;
			
			// aapt resource value: 0x7f070015
			public const int action_bar_activity_content = 2131165205;
			
			// aapt resource value: 0x7f07001e
			public const int action_bar_container = 2131165214;
			
			// aapt resource value: 0x7f070022
			public const int action_bar_overlay_layout = 2131165218;
			
			// aapt resource value: 0x7f07001d
			public const int action_bar_root = 2131165213;
			
			// aapt resource value: 0x7f070026
			public const int action_bar_subtitle = 2131165222;
			
			// aapt resource value: 0x7f070025
			public const int action_bar_title = 2131165221;
			
			// aapt resource value: 0x7f070020
			public const int action_context_bar = 2131165216;
			
			// aapt resource value: 0x7f070016
			public const int action_menu_divider = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int action_menu_presenter = 2131165207;
			
			// aapt resource value: 0x7f070027
			public const int action_mode_close_button = 2131165223;
			
			// aapt resource value: 0x7f070028
			public const int activity_chooser_view_content = 2131165224;
			
			// aapt resource value: 0x7f07000b
			public const int always = 2131165195;
			
			// aapt resource value: 0x7f070011
			public const int beginning = 2131165201;
			
			// aapt resource value: 0x7f070030
			public const int checkbox = 2131165232;
			
			// aapt resource value: 0x7f07000d
			public const int collapseActionView = 2131165197;
			
			// aapt resource value: 0x7f07002b
			public const int default_activity_button = 2131165227;
			
			// aapt resource value: 0x7f07000e
			public const int dialog = 2131165198;
			
			// aapt resource value: 0x7f070008
			public const int disableHome = 2131165192;
			
			// aapt resource value: 0x7f07000f
			public const int dropdown = 2131165199;
			
			// aapt resource value: 0x7f070033
			public const int edit_query = 2131165235;
			
			// aapt resource value: 0x7f070013
			public const int end = 2131165203;
			
			// aapt resource value: 0x7f070029
			public const int expand_activities_button = 2131165225;
			
			// aapt resource value: 0x7f07002f
			public const int expanded_menu = 2131165231;
			
			// aapt resource value: 0x7f070014
			public const int home = 2131165204;
			
			// aapt resource value: 0x7f070005
			public const int homeAsUp = 2131165189;
			
			// aapt resource value: 0x7f07001c
			public const int hybrid = 2131165212;
			
			// aapt resource value: 0x7f07002d
			public const int icon = 2131165229;
			
			// aapt resource value: 0x7f07000a
			public const int ifRoom = 2131165194;
			
			// aapt resource value: 0x7f07002a
			public const int image = 2131165226;
			
			// aapt resource value: 0x7f070001
			public const int listMode = 2131165185;
			
			// aapt resource value: 0x7f07002c
			public const int list_item = 2131165228;
			
			// aapt resource value: 0x7f070042
			public const int media_route_control_frame = 2131165250;
			
			// aapt resource value: 0x7f070043
			public const int media_route_disconnect_button = 2131165251;
			
			// aapt resource value: 0x7f07003f
			public const int media_route_list = 2131165247;
			
			// aapt resource value: 0x7f070040
			public const int media_route_volume_layout = 2131165248;
			
			// aapt resource value: 0x7f070041
			public const int media_route_volume_slider = 2131165249;
			
			// aapt resource value: 0x7f070012
			public const int middle = 2131165202;
			
			// aapt resource value: 0x7f070009
			public const int never = 2131165193;
			
			// aapt resource value: 0x7f070010
			public const int none = 2131165200;
			
			// aapt resource value: 0x7f070000
			public const int normal = 2131165184;
			
			// aapt resource value: 0x7f070018
			public const int progress_circular = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int progress_horizontal = 2131165209;
			
			// aapt resource value: 0x7f070032
			public const int radio = 2131165234;
			
			// aapt resource value: 0x7f07001a
			public const int satellite = 2131165210;
			
			// aapt resource value: 0x7f070035
			public const int search_badge = 2131165237;
			
			// aapt resource value: 0x7f070034
			public const int search_bar = 2131165236;
			
			// aapt resource value: 0x7f070036
			public const int search_button = 2131165238;
			
			// aapt resource value: 0x7f07003b
			public const int search_close_btn = 2131165243;
			
			// aapt resource value: 0x7f070037
			public const int search_edit_frame = 2131165239;
			
			// aapt resource value: 0x7f07003d
			public const int search_go_btn = 2131165245;
			
			// aapt resource value: 0x7f070038
			public const int search_mag_icon = 2131165240;
			
			// aapt resource value: 0x7f070039
			public const int search_plate = 2131165241;
			
			// aapt resource value: 0x7f07003a
			public const int search_src_text = 2131165242;
			
			// aapt resource value: 0x7f07003e
			public const int search_voice_btn = 2131165246;
			
			// aapt resource value: 0x7f070031
			public const int shortcut = 2131165233;
			
			// aapt resource value: 0x7f070007
			public const int showCustom = 2131165191;
			
			// aapt resource value: 0x7f070004
			public const int showHome = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int showTitle = 2131165190;
			
			// aapt resource value: 0x7f070021
			public const int split_action_bar = 2131165217;
			
			// aapt resource value: 0x7f07003c
			public const int submit_area = 2131165244;
			
			// aapt resource value: 0x7f070002
			public const int tabMode = 2131165186;
			
			// aapt resource value: 0x7f07001b
			public const int terrain = 2131165211;
			
			// aapt resource value: 0x7f07002e
			public const int title = 2131165230;
			
			// aapt resource value: 0x7f070023
			public const int top_action_bar = 2131165219;
			
			// aapt resource value: 0x7f070024
			public const int up = 2131165220;
			
			// aapt resource value: 0x7f070003
			public const int useLogo = 2131165187;
			
			// aapt resource value: 0x7f07000c
			public const int withText = 2131165196;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f0b0000
			public const int abc_max_action_buttons = 2131427328;
			
			// aapt resource value: 0x7f0b0001
			public const int google_play_services_version = 2131427329;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int abc_action_bar_decor = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int abc_action_bar_decor_include = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int abc_action_bar_decor_overlay = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int abc_action_bar_home = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int abc_action_bar_tab = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int abc_action_bar_tabbar = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int abc_action_bar_title_item = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int abc_action_bar_view_list_nav_layout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int abc_action_menu_item_layout = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int abc_action_menu_layout = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int abc_action_mode_bar = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int abc_action_mode_close_item = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int abc_activity_chooser_view = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int abc_activity_chooser_view_include = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int abc_activity_chooser_view_list_item = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int abc_expanded_menu_layout = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int abc_list_menu_item_checkbox = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int abc_list_menu_item_icon = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int abc_list_menu_item_layout = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int abc_list_menu_item_radio = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int abc_popup_menu_item_layout = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int abc_search_dropdown_item_icons_2line = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int abc_search_view = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int abc_simple_decor = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int mr_media_route_chooser_dialog = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int mr_media_route_controller_dialog = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int mr_media_route_list_item = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int support_simple_spinner_dropdown_item = 2130903067;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050007
			public const int abc_action_bar_home_description = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int abc_action_bar_up_description = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int abc_action_menu_overflow_description = 2131034121;
			
			// aapt resource value: 0x7f050006
			public const int abc_action_mode_done = 2131034118;
			
			// aapt resource value: 0x7f050010
			public const int abc_activity_chooser_view_see_all = 2131034128;
			
			// aapt resource value: 0x7f05000f
			public const int abc_activitychooserview_choose_application = 2131034127;
			
			// aapt resource value: 0x7f05000c
			public const int abc_searchview_description_clear = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int abc_searchview_description_query = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int abc_searchview_description_search = 2131034122;
			
			// aapt resource value: 0x7f05000d
			public const int abc_searchview_description_submit = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int abc_searchview_description_voice = 2131034126;
			
			// aapt resource value: 0x7f050012
			public const int abc_shareactionprovider_share_with = 2131034130;
			
			// aapt resource value: 0x7f050011
			public const int abc_shareactionprovider_share_with_application = 2131034129;
			
			// aapt resource value: 0x7f050028
			public const int auth_client_needs_enabling_title = 2131034152;
			
			// aapt resource value: 0x7f050029
			public const int auth_client_needs_installation_title = 2131034153;
			
			// aapt resource value: 0x7f05002a
			public const int auth_client_needs_update_title = 2131034154;
			
			// aapt resource value: 0x7f05002b
			public const int auth_client_play_services_err_notification_msg = 2131034155;
			
			// aapt resource value: 0x7f05002c
			public const int auth_client_requested_by_msg = 2131034156;
			
			// aapt resource value: 0x7f050027
			public const int auth_client_using_bad_version_title = 2131034151;
			
			// aapt resource value: 0x7f050019
			public const int common_google_play_services_enable_button = 2131034137;
			
			// aapt resource value: 0x7f050018
			public const int common_google_play_services_enable_text = 2131034136;
			
			// aapt resource value: 0x7f050017
			public const int common_google_play_services_enable_title = 2131034135;
			
			// aapt resource value: 0x7f050016
			public const int common_google_play_services_install_button = 2131034134;
			
			// aapt resource value: 0x7f050014
			public const int common_google_play_services_install_text_phone = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int common_google_play_services_install_text_tablet = 2131034133;
			
			// aapt resource value: 0x7f050013
			public const int common_google_play_services_install_title = 2131034131;
			
			// aapt resource value: 0x7f05001f
			public const int common_google_play_services_invalid_account_text = 2131034143;
			
			// aapt resource value: 0x7f05001e
			public const int common_google_play_services_invalid_account_title = 2131034142;
			
			// aapt resource value: 0x7f05001d
			public const int common_google_play_services_network_error_text = 2131034141;
			
			// aapt resource value: 0x7f05001c
			public const int common_google_play_services_network_error_title = 2131034140;
			
			// aapt resource value: 0x7f050020
			public const int common_google_play_services_unknown_issue = 2131034144;
			
			// aapt resource value: 0x7f050023
			public const int common_google_play_services_unsupported_date_text = 2131034147;
			
			// aapt resource value: 0x7f050022
			public const int common_google_play_services_unsupported_text = 2131034146;
			
			// aapt resource value: 0x7f050021
			public const int common_google_play_services_unsupported_title = 2131034145;
			
			// aapt resource value: 0x7f050024
			public const int common_google_play_services_update_button = 2131034148;
			
			// aapt resource value: 0x7f05001b
			public const int common_google_play_services_update_text = 2131034139;
			
			// aapt resource value: 0x7f05001a
			public const int common_google_play_services_update_title = 2131034138;
			
			// aapt resource value: 0x7f050025
			public const int common_signin_button_text = 2131034149;
			
			// aapt resource value: 0x7f050026
			public const int common_signin_button_text_long = 2131034150;
			
			// aapt resource value: 0x7f05002d
			public const int location_client_powered_by_google = 2131034157;
			
			// aapt resource value: 0x7f050002
			public const int mr_media_route_button_content_description = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int mr_media_route_chooser_searching = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int mr_media_route_chooser_title = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int mr_media_route_controller_disconnect = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int mr_system_route_name = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int mr_user_route_category_name = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060067
			public const int TextAppearance_AppCompat_Base_CompactMenu_Dialog = 2131099751;
			
			// aapt resource value: 0x7f060071
			public const int TextAppearance_AppCompat_Base_SearchResult = 2131099761;
			
			// aapt resource value: 0x7f060073
			public const int TextAppearance_AppCompat_Base_SearchResult_Subtitle = 2131099763;
			
			// aapt resource value: 0x7f060072
			public const int TextAppearance_AppCompat_Base_SearchResult_Title = 2131099762;
			
			// aapt resource value: 0x7f06006d
			public const int TextAppearance_AppCompat_Base_Widget_PopupMenu_Large = 2131099757;
			
			// aapt resource value: 0x7f06006e
			public const int TextAppearance_AppCompat_Base_Widget_PopupMenu_Small = 2131099758;
			
			// aapt resource value: 0x7f060074
			public const int TextAppearance_AppCompat_Light_Base_SearchResult = 2131099764;
			
			// aapt resource value: 0x7f060076
			public const int TextAppearance_AppCompat_Light_Base_SearchResult_Subtitle = 2131099766;
			
			// aapt resource value: 0x7f060075
			public const int TextAppearance_AppCompat_Light_Base_SearchResult_Title = 2131099765;
			
			// aapt resource value: 0x7f06006f
			public const int TextAppearance_AppCompat_Light_Base_Widget_PopupMenu_Large = 2131099759;
			
			// aapt resource value: 0x7f060070
			public const int TextAppearance_AppCompat_Light_Base_Widget_PopupMenu_Small = 2131099760;
			
			// aapt resource value: 0x7f060039
			public const int TextAppearance_AppCompat_Light_SearchResult_Subtitle = 2131099705;
			
			// aapt resource value: 0x7f060038
			public const int TextAppearance_AppCompat_Light_SearchResult_Title = 2131099704;
			
			// aapt resource value: 0x7f060034
			public const int TextAppearance_AppCompat_Light_Widget_PopupMenu_Large = 2131099700;
			
			// aapt resource value: 0x7f060035
			public const int TextAppearance_AppCompat_Light_Widget_PopupMenu_Small = 2131099701;
			
			// aapt resource value: 0x7f060037
			public const int TextAppearance_AppCompat_SearchResult_Subtitle = 2131099703;
			
			// aapt resource value: 0x7f060036
			public const int TextAppearance_AppCompat_SearchResult_Title = 2131099702;
			
			// aapt resource value: 0x7f06001e
			public const int TextAppearance_AppCompat_Widget_ActionBar_Menu = 2131099678;
			
			// aapt resource value: 0x7f06000a
			public const int TextAppearance_AppCompat_Widget_ActionBar_Subtitle = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int TextAppearance_AppCompat_Widget_ActionBar_Subtitle_Inverse = 2131099660;
			
			// aapt resource value: 0x7f060009
			public const int TextAppearance_AppCompat_Widget_ActionBar_Title = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int TextAppearance_AppCompat_Widget_ActionBar_Title_Inverse = 2131099659;
			
			// aapt resource value: 0x7f060022
			public const int TextAppearance_AppCompat_Widget_ActionMode_Subtitle = 2131099682;
			
			// aapt resource value: 0x7f060024
			public const int TextAppearance_AppCompat_Widget_ActionMode_Subtitle_Inverse = 2131099684;
			
			// aapt resource value: 0x7f060021
			public const int TextAppearance_AppCompat_Widget_ActionMode_Title = 2131099681;
			
			// aapt resource value: 0x7f060023
			public const int TextAppearance_AppCompat_Widget_ActionMode_Title_Inverse = 2131099683;
			
			// aapt resource value: 0x7f060058
			public const int TextAppearance_AppCompat_Widget_Base_ActionBar_Menu = 2131099736;
			
			// aapt resource value: 0x7f06005a
			public const int TextAppearance_AppCompat_Widget_Base_ActionBar_Subtitle = 2131099738;
			
			// aapt resource value: 0x7f06005c
			public const int TextAppearance_AppCompat_Widget_Base_ActionBar_Subtitle_Inverse = 2131099740;
			
			// aapt resource value: 0x7f060059
			public const int TextAppearance_AppCompat_Widget_Base_ActionBar_Title = 2131099737;
			
			// aapt resource value: 0x7f06005b
			public const int TextAppearance_AppCompat_Widget_Base_ActionBar_Title_Inverse = 2131099739;
			
			// aapt resource value: 0x7f060055
			public const int TextAppearance_AppCompat_Widget_Base_ActionMode_Subtitle = 2131099733;
			
			// aapt resource value: 0x7f060057
			public const int TextAppearance_AppCompat_Widget_Base_ActionMode_Subtitle_Inverse = 2131099735;
			
			// aapt resource value: 0x7f060054
			public const int TextAppearance_AppCompat_Widget_Base_ActionMode_Title = 2131099732;
			
			// aapt resource value: 0x7f060056
			public const int TextAppearance_AppCompat_Widget_Base_ActionMode_Title_Inverse = 2131099734;
			
			// aapt resource value: 0x7f060065
			public const int TextAppearance_AppCompat_Widget_Base_DropDownItem = 2131099749;
			
			// aapt resource value: 0x7f060025
			public const int TextAppearance_AppCompat_Widget_DropDownItem = 2131099685;
			
			// aapt resource value: 0x7f060032
			public const int TextAppearance_AppCompat_Widget_PopupMenu_Large = 2131099698;
			
			// aapt resource value: 0x7f060033
			public const int TextAppearance_AppCompat_Widget_PopupMenu_Small = 2131099699;
			
			// aapt resource value: 0x7f060066
			public const int TextAppearance_Widget_AppCompat_Base_ExpandedMenu_Item = 2131099750;
			
			// aapt resource value: 0x7f06002c
			public const int TextAppearance_Widget_AppCompat_ExpandedMenu_Item = 2131099692;
			
			// aapt resource value: 0x7f06007b
			public const int Theme_AppCompat = 2131099771;
			
			// aapt resource value: 0x7f060087
			public const int Theme_AppCompat_Base_CompactMenu = 2131099783;
			
			// aapt resource value: 0x7f060088
			public const int Theme_AppCompat_Base_CompactMenu_Dialog = 2131099784;
			
			// aapt resource value: 0x7f060080
			public const int Theme_AppCompat_CompactMenu = 2131099776;
			
			// aapt resource value: 0x7f060081
			public const int Theme_AppCompat_CompactMenu_Dialog = 2131099777;
			
			// aapt resource value: 0x7f06007e
			public const int Theme_AppCompat_DialogWhenLarge = 2131099774;
			
			// aapt resource value: 0x7f06007c
			public const int Theme_AppCompat_Light = 2131099772;
			
			// aapt resource value: 0x7f06007d
			public const int Theme_AppCompat_Light_DarkActionBar = 2131099773;
			
			// aapt resource value: 0x7f06007f
			public const int Theme_AppCompat_Light_DialogWhenLarge = 2131099775;
			
			// aapt resource value: 0x7f060082
			public const int Theme_Base = 2131099778;
			
			// aapt resource value: 0x7f060084
			public const int Theme_Base_AppCompat = 2131099780;
			
			// aapt resource value: 0x7f06008b
			public const int Theme_Base_AppCompat_Dialog_FixedSize = 2131099787;
			
			// aapt resource value: 0x7f06008c
			public const int Theme_Base_AppCompat_Dialog_Light_FixedSize = 2131099788;
			
			// aapt resource value: 0x7f060089
			public const int Theme_Base_AppCompat_DialogWhenLarge = 2131099785;
			
			// aapt resource value: 0x7f06008d
			public const int Theme_Base_AppCompat_DialogWhenLarge_Base = 2131099789;
			
			// aapt resource value: 0x7f060085
			public const int Theme_Base_AppCompat_Light = 2131099781;
			
			// aapt resource value: 0x7f060086
			public const int Theme_Base_AppCompat_Light_DarkActionBar = 2131099782;
			
			// aapt resource value: 0x7f06008a
			public const int Theme_Base_AppCompat_Light_DialogWhenLarge = 2131099786;
			
			// aapt resource value: 0x7f06008e
			public const int Theme_Base_AppCompat_Light_DialogWhenLarge_Base = 2131099790;
			
			// aapt resource value: 0x7f060083
			public const int Theme_Base_Light = 2131099779;
			
			// aapt resource value: 0x7f060002
			public const int Theme_MediaRouter = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int Theme_MediaRouter_Light = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int Widget_AppCompat_ActionBar = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int Widget_AppCompat_ActionBar_Solid = 2131099654;
			
			// aapt resource value: 0x7f060015
			public const int Widget_AppCompat_ActionBar_TabBar = 2131099669;
			
			// aapt resource value: 0x7f06001b
			public const int Widget_AppCompat_ActionBar_TabText = 2131099675;
			
			// aapt resource value: 0x7f060018
			public const int Widget_AppCompat_ActionBar_TabView = 2131099672;
			
			// aapt resource value: 0x7f06000f
			public const int Widget_AppCompat_ActionButton = 2131099663;
			
			// aapt resource value: 0x7f060011
			public const int Widget_AppCompat_ActionButton_CloseMode = 2131099665;
			
			// aapt resource value: 0x7f060013
			public const int Widget_AppCompat_ActionButton_Overflow = 2131099667;
			
			// aapt resource value: 0x7f06001f
			public const int Widget_AppCompat_ActionMode = 2131099679;
			
			// aapt resource value: 0x7f06003c
			public const int Widget_AppCompat_ActivityChooserView = 2131099708;
			
			// aapt resource value: 0x7f06003a
			public const int Widget_AppCompat_AutoCompleteTextView = 2131099706;
			
			// aapt resource value: 0x7f06003e
			public const int Widget_AppCompat_Base_ActionBar = 2131099710;
			
			// aapt resource value: 0x7f060040
			public const int Widget_AppCompat_Base_ActionBar_Solid = 2131099712;
			
			// aapt resource value: 0x7f060049
			public const int Widget_AppCompat_Base_ActionBar_TabBar = 2131099721;
			
			// aapt resource value: 0x7f06004f
			public const int Widget_AppCompat_Base_ActionBar_TabText = 2131099727;
			
			// aapt resource value: 0x7f06004c
			public const int Widget_AppCompat_Base_ActionBar_TabView = 2131099724;
			
			// aapt resource value: 0x7f060043
			public const int Widget_AppCompat_Base_ActionButton = 2131099715;
			
			// aapt resource value: 0x7f060045
			public const int Widget_AppCompat_Base_ActionButton_CloseMode = 2131099717;
			
			// aapt resource value: 0x7f060047
			public const int Widget_AppCompat_Base_ActionButton_Overflow = 2131099719;
			
			// aapt resource value: 0x7f060052
			public const int Widget_AppCompat_Base_ActionMode = 2131099730;
			
			// aapt resource value: 0x7f060079
			public const int Widget_AppCompat_Base_ActivityChooserView = 2131099769;
			
			// aapt resource value: 0x7f060077
			public const int Widget_AppCompat_Base_AutoCompleteTextView = 2131099767;
			
			// aapt resource value: 0x7f060061
			public const int Widget_AppCompat_Base_DropDownItem_Spinner = 2131099745;
			
			// aapt resource value: 0x7f060069
			public const int Widget_AppCompat_Base_ListPopupWindow = 2131099753;
			
			// aapt resource value: 0x7f060063
			public const int Widget_AppCompat_Base_ListView_DropDown = 2131099747;
			
			// aapt resource value: 0x7f060068
			public const int Widget_AppCompat_Base_ListView_Menu = 2131099752;
			
			// aapt resource value: 0x7f06006b
			public const int Widget_AppCompat_Base_PopupMenu = 2131099755;
			
			// aapt resource value: 0x7f06005e
			public const int Widget_AppCompat_Base_ProgressBar = 2131099742;
			
			// aapt resource value: 0x7f06005d
			public const int Widget_AppCompat_Base_ProgressBar_Horizontal = 2131099741;
			
			// aapt resource value: 0x7f06005f
			public const int Widget_AppCompat_Base_Spinner = 2131099743;
			
			// aapt resource value: 0x7f060028
			public const int Widget_AppCompat_DropDownItem_Spinner = 2131099688;
			
			// aapt resource value: 0x7f060005
			public const int Widget_AppCompat_Light_ActionBar = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int Widget_AppCompat_Light_ActionBar_Solid = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int Widget_AppCompat_Light_ActionBar_Solid_Inverse = 2131099656;
			
			// aapt resource value: 0x7f060016
			public const int Widget_AppCompat_Light_ActionBar_TabBar = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int Widget_AppCompat_Light_ActionBar_TabBar_Inverse = 2131099671;
			
			// aapt resource value: 0x7f06001c
			public const int Widget_AppCompat_Light_ActionBar_TabText = 2131099676;
			
			// aapt resource value: 0x7f06001d
			public const int Widget_AppCompat_Light_ActionBar_TabText_Inverse = 2131099677;
			
			// aapt resource value: 0x7f060019
			public const int Widget_AppCompat_Light_ActionBar_TabView = 2131099673;
			
			// aapt resource value: 0x7f06001a
			public const int Widget_AppCompat_Light_ActionBar_TabView_Inverse = 2131099674;
			
			// aapt resource value: 0x7f060010
			public const int Widget_AppCompat_Light_ActionButton = 2131099664;
			
			// aapt resource value: 0x7f060012
			public const int Widget_AppCompat_Light_ActionButton_CloseMode = 2131099666;
			
			// aapt resource value: 0x7f060014
			public const int Widget_AppCompat_Light_ActionButton_Overflow = 2131099668;
			
			// aapt resource value: 0x7f060020
			public const int Widget_AppCompat_Light_ActionMode_Inverse = 2131099680;
			
			// aapt resource value: 0x7f06003d
			public const int Widget_AppCompat_Light_ActivityChooserView = 2131099709;
			
			// aapt resource value: 0x7f06003b
			public const int Widget_AppCompat_Light_AutoCompleteTextView = 2131099707;
			
			// aapt resource value: 0x7f06003f
			public const int Widget_AppCompat_Light_Base_ActionBar = 2131099711;
			
			// aapt resource value: 0x7f060041
			public const int Widget_AppCompat_Light_Base_ActionBar_Solid = 2131099713;
			
			// aapt resource value: 0x7f060042
			public const int Widget_AppCompat_Light_Base_ActionBar_Solid_Inverse = 2131099714;
			
			// aapt resource value: 0x7f06004a
			public const int Widget_AppCompat_Light_Base_ActionBar_TabBar = 2131099722;
			
			// aapt resource value: 0x7f06004b
			public const int Widget_AppCompat_Light_Base_ActionBar_TabBar_Inverse = 2131099723;
			
			// aapt resource value: 0x7f060050
			public const int Widget_AppCompat_Light_Base_ActionBar_TabText = 2131099728;
			
			// aapt resource value: 0x7f060051
			public const int Widget_AppCompat_Light_Base_ActionBar_TabText_Inverse = 2131099729;
			
			// aapt resource value: 0x7f06004d
			public const int Widget_AppCompat_Light_Base_ActionBar_TabView = 2131099725;
			
			// aapt resource value: 0x7f06004e
			public const int Widget_AppCompat_Light_Base_ActionBar_TabView_Inverse = 2131099726;
			
			// aapt resource value: 0x7f060044
			public const int Widget_AppCompat_Light_Base_ActionButton = 2131099716;
			
			// aapt resource value: 0x7f060046
			public const int Widget_AppCompat_Light_Base_ActionButton_CloseMode = 2131099718;
			
			// aapt resource value: 0x7f060048
			public const int Widget_AppCompat_Light_Base_ActionButton_Overflow = 2131099720;
			
			// aapt resource value: 0x7f060053
			public const int Widget_AppCompat_Light_Base_ActionMode_Inverse = 2131099731;
			
			// aapt resource value: 0x7f06007a
			public const int Widget_AppCompat_Light_Base_ActivityChooserView = 2131099770;
			
			// aapt resource value: 0x7f060078
			public const int Widget_AppCompat_Light_Base_AutoCompleteTextView = 2131099768;
			
			// aapt resource value: 0x7f060062
			public const int Widget_AppCompat_Light_Base_DropDownItem_Spinner = 2131099746;
			
			// aapt resource value: 0x7f06006a
			public const int Widget_AppCompat_Light_Base_ListPopupWindow = 2131099754;
			
			// aapt resource value: 0x7f060064
			public const int Widget_AppCompat_Light_Base_ListView_DropDown = 2131099748;
			
			// aapt resource value: 0x7f06006c
			public const int Widget_AppCompat_Light_Base_PopupMenu = 2131099756;
			
			// aapt resource value: 0x7f060060
			public const int Widget_AppCompat_Light_Base_Spinner = 2131099744;
			
			// aapt resource value: 0x7f060029
			public const int Widget_AppCompat_Light_DropDownItem_Spinner = 2131099689;
			
			// aapt resource value: 0x7f06002e
			public const int Widget_AppCompat_Light_ListPopupWindow = 2131099694;
			
			// aapt resource value: 0x7f06002b
			public const int Widget_AppCompat_Light_ListView_DropDown = 2131099691;
			
			// aapt resource value: 0x7f060030
			public const int Widget_AppCompat_Light_PopupMenu = 2131099696;
			
			// aapt resource value: 0x7f060027
			public const int Widget_AppCompat_Light_Spinner_DropDown_ActionBar = 2131099687;
			
			// aapt resource value: 0x7f06002d
			public const int Widget_AppCompat_ListPopupWindow = 2131099693;
			
			// aapt resource value: 0x7f06002a
			public const int Widget_AppCompat_ListView_DropDown = 2131099690;
			
			// aapt resource value: 0x7f060031
			public const int Widget_AppCompat_ListView_Menu = 2131099697;
			
			// aapt resource value: 0x7f06002f
			public const int Widget_AppCompat_PopupMenu = 2131099695;
			
			// aapt resource value: 0x7f06000e
			public const int Widget_AppCompat_ProgressBar = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int Widget_AppCompat_ProgressBar_Horizontal = 2131099661;
			
			// aapt resource value: 0x7f060026
			public const int Widget_AppCompat_Spinner_DropDown_ActionBar = 2131099686;
			
			// aapt resource value: 0x7f060001
			public const int Widget_MediaRouter_Light_MediaRouteButton = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Widget_MediaRouter_MediaRouteButton = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ActionBar = new int[] {
					2130772010,
					2130772011,
					2130772012,
					2130772013,
					2130772014,
					2130772015,
					2130772016,
					2130772017,
					2130772018,
					2130772019,
					2130772020,
					2130772021,
					2130772022,
					2130772023,
					2130772024,
					2130772025,
					2130772026,
					2130772027,
					2130772028};
			
			// aapt resource value: 10
			public const int ActionBar_background = 10;
			
			// aapt resource value: 12
			public const int ActionBar_backgroundSplit = 12;
			
			// aapt resource value: 11
			public const int ActionBar_backgroundStacked = 11;
			
			// aapt resource value: 13
			public const int ActionBar_customNavigationLayout = 13;
			
			// aapt resource value: 3
			public const int ActionBar_displayOptions = 3;
			
			// aapt resource value: 9
			public const int ActionBar_divider = 9;
			
			// aapt resource value: 1
			public const int ActionBar_height = 1;
			
			// aapt resource value: 14
			public const int ActionBar_homeLayout = 14;
			
			// aapt resource value: 7
			public const int ActionBar_icon = 7;
			
			// aapt resource value: 16
			public const int ActionBar_indeterminateProgressStyle = 16;
			
			// aapt resource value: 18
			public const int ActionBar_itemPadding = 18;
			
			// aapt resource value: 8
			public const int ActionBar_logo = 8;
			
			// aapt resource value: 2
			public const int ActionBar_navigationMode = 2;
			
			// aapt resource value: 17
			public const int ActionBar_progressBarPadding = 17;
			
			// aapt resource value: 15
			public const int ActionBar_progressBarStyle = 15;
			
			// aapt resource value: 4
			public const int ActionBar_subtitle = 4;
			
			// aapt resource value: 6
			public const int ActionBar_subtitleTextStyle = 6;
			
			// aapt resource value: 0
			public const int ActionBar_title = 0;
			
			// aapt resource value: 5
			public const int ActionBar_titleTextStyle = 5;
			
			public static int[] ActionBarLayout = new int[] {
					16842931};
			
			// aapt resource value: 0
			public const int ActionBarLayout_android_layout_gravity = 0;
			
			public static int[] ActionBarWindow = new int[] {
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 0
			public const int ActionBarWindow_windowActionBar = 0;
			
			// aapt resource value: 1
			public const int ActionBarWindow_windowActionBarOverlay = 1;
			
			// aapt resource value: 6
			public const int ActionBarWindow_windowFixedHeightMajor = 6;
			
			// aapt resource value: 4
			public const int ActionBarWindow_windowFixedHeightMinor = 4;
			
			// aapt resource value: 3
			public const int ActionBarWindow_windowFixedWidthMajor = 3;
			
			// aapt resource value: 5
			public const int ActionBarWindow_windowFixedWidthMinor = 5;
			
			// aapt resource value: 2
			public const int ActionBarWindow_windowSplitActionBar = 2;
			
			public static int[] ActionMenuItemView = new int[] {
					16843071};
			
			// aapt resource value: 0
			public const int ActionMenuItemView_android_minWidth = 0;
			
			public static int[] ActionMenuView;
			
			public static int[] ActionMode = new int[] {
					2130772011,
					2130772015,
					2130772016,
					2130772020,
					2130772022};
			
			// aapt resource value: 3
			public const int ActionMode_background = 3;
			
			// aapt resource value: 4
			public const int ActionMode_backgroundSplit = 4;
			
			// aapt resource value: 0
			public const int ActionMode_height = 0;
			
			// aapt resource value: 2
			public const int ActionMode_subtitleTextStyle = 2;
			
			// aapt resource value: 1
			public const int ActionMode_titleTextStyle = 1;
			
			public static int[] ActivityChooserView = new int[] {
					2130772079,
					2130772080};
			
			// aapt resource value: 1
			public const int ActivityChooserView_expandActivityOverflowButtonDrawable = 1;
			
			// aapt resource value: 0
			public const int ActivityChooserView_initialActivityCount = 0;
			
			public static int[] AdsAttrs = new int[] {
					2130772083,
					2130772084,
					2130772085};
			
			// aapt resource value: 0
			public const int AdsAttrs_adSize = 0;
			
			// aapt resource value: 1
			public const int AdsAttrs_adSizes = 1;
			
			// aapt resource value: 2
			public const int AdsAttrs_adUnitId = 2;
			
			public static int[] CompatTextView = new int[] {
					2130772082};
			
			// aapt resource value: 0
			public const int CompatTextView_textAllCaps = 0;
			
			public static int[] LinearLayoutICS = new int[] {
					2130772019,
					2130772058,
					2130772059};
			
			// aapt resource value: 0
			public const int LinearLayoutICS_divider = 0;
			
			// aapt resource value: 2
			public const int LinearLayoutICS_dividerPadding = 2;
			
			// aapt resource value: 1
			public const int LinearLayoutICS_showDividers = 1;
			
			public static int[] MapAttrs = new int[] {
					2130772086,
					2130772087,
					2130772088,
					2130772089,
					2130772090,
					2130772091,
					2130772092,
					2130772093,
					2130772094,
					2130772095,
					2130772096,
					2130772097,
					2130772098,
					2130772099};
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 6
			public const int MapAttrs_uiCompass = 6;
			
			// aapt resource value: 7
			public const int MapAttrs_uiRotateGestures = 7;
			
			// aapt resource value: 8
			public const int MapAttrs_uiScrollGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiTiltGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiZoomControls = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomGestures = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_useViewLifecycle = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_zOrderOnTop = 13;
			
			public static int[] MediaRouteButton = new int[] {
					16843071,
					16843072,
					2130771968};
			
			// aapt resource value: 1
			public const int MediaRouteButton_android_minHeight = 1;
			
			// aapt resource value: 0
			public const int MediaRouteButton_android_minWidth = 0;
			
			// aapt resource value: 2
			public const int MediaRouteButton_externalRouteEnabledDrawable = 2;
			
			public static int[] MenuGroup = new int[] {
					16842766,
					16842960,
					16843156,
					16843230,
					16843231,
					16843232};
			
			// aapt resource value: 5
			public const int MenuGroup_android_checkableBehavior = 5;
			
			// aapt resource value: 0
			public const int MenuGroup_android_enabled = 0;
			
			// aapt resource value: 1
			public const int MenuGroup_android_id = 1;
			
			// aapt resource value: 3
			public const int MenuGroup_android_menuCategory = 3;
			
			// aapt resource value: 4
			public const int MenuGroup_android_orderInCategory = 4;
			
			// aapt resource value: 2
			public const int MenuGroup_android_visible = 2;
			
			public static int[] MenuItem = new int[] {
					16842754,
					16842766,
					16842960,
					16843014,
					16843156,
					16843230,
					16843231,
					16843233,
					16843234,
					16843235,
					16843236,
					16843237,
					16843375,
					2130772050,
					2130772051,
					2130772052,
					2130772053};
			
			// aapt resource value: 14
			public const int MenuItem_actionLayout = 14;
			
			// aapt resource value: 16
			public const int MenuItem_actionProviderClass = 16;
			
			// aapt resource value: 15
			public const int MenuItem_actionViewClass = 15;
			
			// aapt resource value: 9
			public const int MenuItem_android_alphabeticShortcut = 9;
			
			// aapt resource value: 11
			public const int MenuItem_android_checkable = 11;
			
			// aapt resource value: 3
			public const int MenuItem_android_checked = 3;
			
			// aapt resource value: 1
			public const int MenuItem_android_enabled = 1;
			
			// aapt resource value: 0
			public const int MenuItem_android_icon = 0;
			
			// aapt resource value: 2
			public const int MenuItem_android_id = 2;
			
			// aapt resource value: 5
			public const int MenuItem_android_menuCategory = 5;
			
			// aapt resource value: 10
			public const int MenuItem_android_numericShortcut = 10;
			
			// aapt resource value: 12
			public const int MenuItem_android_onClick = 12;
			
			// aapt resource value: 6
			public const int MenuItem_android_orderInCategory = 6;
			
			// aapt resource value: 7
			public const int MenuItem_android_title = 7;
			
			// aapt resource value: 8
			public const int MenuItem_android_titleCondensed = 8;
			
			// aapt resource value: 4
			public const int MenuItem_android_visible = 4;
			
			// aapt resource value: 13
			public const int MenuItem_showAsAction = 13;
			
			public static int[] MenuView = new int[] {
					16842926,
					16843052,
					16843053,
					16843054,
					16843055,
					16843056,
					16843057,
					16843948};
			
			// aapt resource value: 4
			public const int MenuView_android_headerBackground = 4;
			
			// aapt resource value: 2
			public const int MenuView_android_horizontalDivider = 2;
			
			// aapt resource value: 5
			public const int MenuView_android_itemBackground = 5;
			
			// aapt resource value: 6
			public const int MenuView_android_itemIconDisabledAlpha = 6;
			
			// aapt resource value: 1
			public const int MenuView_android_itemTextAppearance = 1;
			
			// aapt resource value: 7
			public const int MenuView_android_preserveIconSpacing = 7;
			
			// aapt resource value: 3
			public const int MenuView_android_verticalDivider = 3;
			
			// aapt resource value: 0
			public const int MenuView_android_windowAnimationStyle = 0;
			
			public static int[] SearchView = new int[] {
					16843039,
					16843296,
					16843364,
					2130772063,
					2130772064};
			
			// aapt resource value: 2
			public const int SearchView_android_imeOptions = 2;
			
			// aapt resource value: 1
			public const int SearchView_android_inputType = 1;
			
			// aapt resource value: 0
			public const int SearchView_android_maxWidth = 0;
			
			// aapt resource value: 3
			public const int SearchView_iconifiedByDefault = 3;
			
			// aapt resource value: 4
			public const int SearchView_queryHint = 4;
			
			public static int[] Spinner = new int[] {
					16842927,
					16843125,
					16843126,
					16843362,
					16843436,
					16843437,
					2130772054,
					2130772055,
					2130772056,
					2130772057};
			
			// aapt resource value: 4
			public const int Spinner_android_dropDownHorizontalOffset = 4;
			
			// aapt resource value: 1
			public const int Spinner_android_dropDownSelector = 1;
			
			// aapt resource value: 5
			public const int Spinner_android_dropDownVerticalOffset = 5;
			
			// aapt resource value: 3
			public const int Spinner_android_dropDownWidth = 3;
			
			// aapt resource value: 0
			public const int Spinner_android_gravity = 0;
			
			// aapt resource value: 2
			public const int Spinner_android_popupBackground = 2;
			
			// aapt resource value: 9
			public const int Spinner_disableChildrenWhenDisabled = 9;
			
			// aapt resource value: 8
			public const int Spinner_popupPromptView = 8;
			
			// aapt resource value: 6
			public const int Spinner_prompt = 6;
			
			// aapt resource value: 7
			public const int Spinner_spinnerMode = 7;
			
			public static int[] Theme = new int[] {
					2130772044,
					2130772045,
					2130772046,
					2130772047,
					2130772048,
					2130772049};
			
			// aapt resource value: 0
			public const int Theme_actionDropDownStyle = 0;
			
			// aapt resource value: 1
			public const int Theme_dropdownListPreferredItemHeight = 1;
			
			// aapt resource value: 5
			public const int Theme_listChoiceBackgroundIndicator = 5;
			
			// aapt resource value: 4
			public const int Theme_panelMenuListTheme = 4;
			
			// aapt resource value: 3
			public const int Theme_panelMenuListWidth = 3;
			
			// aapt resource value: 2
			public const int Theme_popupMenuStyle = 2;
			
			public static int[] View = new int[] {
					16842970,
					2130772029,
					2130772030};
			
			// aapt resource value: 0
			public const int View_android_focusable = 0;
			
			// aapt resource value: 2
			public const int View_paddingEnd = 2;
			
			// aapt resource value: 1
			public const int View_paddingStart = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
